language: shell

jobs:
    include:
        - os: linux
          dist: trusty
        - os: linux
          dist: xenial
        - os: linux
          dist: bionic
        - os: osx

script: ./travis.sh && ./test.sh
